// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcsxlhbdrrlfwfrorpyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjc3hsaGJkcnJsZndmcm9ycHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDU1OTIsImV4cCI6MjA3MTYyMTU5Mn0.mn0GXfafRPVwVv0ZZeMsyeU8aJuX6NHKMnkGVkoWHpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});